In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
mfrs =  pd.read_table('FDA-mfrs.csv', names=['mfr_name'])

In [4]:
mfrs.head()

mfr_name
0               OTSUKA
1  OTSUKA PHARM CO LTD
2           PFIZER INC
3   SUN PHARM INDS INC
4  SENTYNL THERAPS INC

In [5]:
mfrs.shape

(363, 1)

In [6]:
mfr_id = np.arange(1, 364)
mfr_id

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [7]:
mfr_name_list = mfrs.mfr_name.unique()
mfr_name_list.size

363

In [8]:
pin = np.random.randint(low=100000, high=999999, size=363)
pin

array([637793, 100913, 610687, 426407, 833147, 331113, 598222, 342326,
       103014, 854114, 141509, 582583, 402404, 173283, 745536, 158099,
       148575, 378942, 822129, 600943, 536366, 506663, 593000, 341731,
       569238, 621119, 466043, 211855, 307681, 845226, 977753, 464719,
       223507, 917537, 544787, 759774, 731708, 423331, 792005, 314173,
       710815, 945920, 431136, 374119, 948000, 845663, 669818, 368656,
       771626, 366096, 871515, 582602, 415276, 594809, 609407, 679907,
       560552, 320624, 727574, 618435, 905490, 327624, 512306, 189264,
       997445, 185794, 772761, 464324, 901542, 199379, 170824, 640710,
       468574, 236742, 147038, 358110, 228672, 143862, 528058, 392618,
       694201, 855653, 146801, 860271, 669574, 790920, 267860, 891651,
       322264, 161443, 494017, 713834, 206694, 615786, 394641, 658724,
       390536, 405015, 598359, 968453, 452665, 107385, 488152, 356696,
       726881, 522633, 895178, 177883, 987687, 936470, 481373, 755759,
      

In [9]:
phone = np.random.randint(low=1000000000, high=9999999999, size=363, dtype='int64')
phone

array([2083135240, 8617796496, 4181850981, 2284108156, 8584127094,
       2138268919, 3870282016, 5996657750, 7222073849, 6751693853,
       8780078469, 9074462781, 7887172631, 7474816525, 1759476645,
       8046630277, 2096314775, 5648385889, 9195410012, 4854814736,
       8482478364, 1665630507, 5790438493, 4960000684, 6183307441,
       5002058092, 1924220490, 4286028405, 7156312274, 5227303121,
       7182119521, 3238414007, 4368580764, 4926893777, 3597084691,
       7513404633, 7974893480, 7216318817, 4080051529, 8517336177,
       6367876550, 5638476809, 3841792785, 5575019232, 6191247464,
       8726151566, 5437840449, 1299891295, 6858899531, 8992903153,
       2391308356, 3308687589, 6432081008, 6046105161, 6132895481,
       5329000173, 1582681972, 3055479869, 8740516419, 1760858797,
       3216848051, 7828385897, 8184306593, 8708755684, 5607382321,
       2271211377, 9190787073, 5613258411, 4962464554, 8697053340,
       2184409527, 2804072782, 6670199052, 7207389019, 9798659

In [10]:
mfrs.mfr_name[1].lower().replace(' ', '')+'@mail.com'

'otsukapharmcoltd@mail.com'

In [11]:
email = mfrs.apply(lambda x: x.mfr_name.lower().replace(' ', '')+'@mail.com', axis=1)
email

0                      otsuka@mail.com
1            otsukapharmcoltd@mail.com
2                   pfizerinc@mail.com
3             sunpharmindsinc@mail.com
4           sentynltherapsinc@mail.com
                    ...               
358    marinuspharmaceuticals@mail.com
359                orexousinc@mail.com
360                sagetherap@mail.com
361                    incyte@mail.com
362                elilillyco@mail.com
Length: 363, dtype: object

In [12]:
cities = ['Kolkata', 'Mohali', 'ABC City', 'DEF City', 'Delhi', 'Mumbai', 'Pune', 'Dehradun']
addr = mfrs.apply(lambda x: random.choice(cities), axis=1)
addr

0        Mumbai
1        Mumbai
2      DEF City
3      Dehradun
4      DEF City
         ...   
358      Mohali
359       Delhi
360      Mohali
361    DEF City
362    Dehradun
Length: 363, dtype: object

In [13]:
myData = {
    'mfr_id': mfr_id,
    'mfr_name': mfr_name_list,
    'address_1': addr,
    'pin': pin,
    'email': email,
    'phone': phone,
}

In [14]:
mfr_table=pd.DataFrame(data=myData)

In [15]:
mfr_table

mfr_id                 mfr_name address_1     pin  \
0         1                   OTSUKA    Mumbai  637793   
1         2      OTSUKA PHARM CO LTD    Mumbai  100913   
2         3               PFIZER INC  DEF City  610687   
3         4       SUN PHARM INDS INC  Dehradun  426407   
4         5      SENTYNL THERAPS INC  DEF City  833147   
..      ...                      ...       ...     ...   
358     359  MARINUS PHARMACEUTICALS    Mohali  138062   
359     360             OREXO US INC     Delhi  393377   
360     361              SAGE THERAP    Mohali  631466   
361     362                   INCYTE  DEF City  116695   
362     363             ELI LILLY CO  Dehradun  554363   

                               email       phone  
0                    otsuka@mail.com  2083135240  
1          otsukapharmcoltd@mail.com  8617796496  
2                 pfizerinc@mail.com  4181850981  
3           sunpharmindsinc@mail.com  2284108156  
4         sentynltherapsinc@mail.com  8584127094  
..                               ...         ...  
358  marinuspharmaceuticals@mail.com  2431021605  
359              orexousinc@mail.com  4897457133  
360              sagetherap@mail.com  2481706637  
361                  incyte@mail.com  6353639317  
362              elilillyco@mail.com  4549571239  

[363 rows x 6 columns]

In [16]:
mfr_table.to_csv('mfrs_data.csv')